http:
  port: "8081"
  
american:
  host: "training-american-ws-khushbu-proxy.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "bd54a51c68f64a14a40a21a62d441a20"
  client_secret: "246C3e0782eB4392B168E84234185eF3" 
 
training:
  host: "ilt.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"